export const strings = {
  // app/layout.tsx
  appTitle: "Document Upload UI",
  appDescription: "Frontend Engineer Interview Assessment",

  // @/components/DocumentUploadWidget.tsx
  none: "None",
  testImport1: "Test Import 1",
  testImport2: "Test Import 2",
  testImport3: "Test Import 3",
  yes: "Yes",
  no: "No",
  single: "Single",
  multiple: "Multiple",
  testClient1: "Test Client 1",
  testClient2: "Test Client 2",
  testClient3: "Test Client 3",
  testClient4: "Test Client 4",
  close: "Close",
  documentUpload: "Document Upload",
  selectImportName: "Select Import Name",
  selectAManifest: "Select a manifest that you’d like to import",
  elapseDataChecking: "Elapse Data Checking:",
  noElapsedDates: "No Elapsed Dates!",
  toleranceWindow: "Tolerance Window:",
  toggle: "Toggle",
  on: "ON",
  off: "OFF",
  pipeBar: "|",
  selectToleranceLevel: "Select Tolerance Level",
  splitSchedule: "Split schedule using social distancing?",
  locationChecking: "Location Checking:",
  allAvailable: "All Available!",
  client: "Client:",
  testingCenter: "Testing Center",
  selectClient: "Select Client",
  dataInTheImportFile:
    "Data in the import file is correct. Please press Continue to import.",
  continueImport: "Continue Import",
  cancel: "Cancel",

  // @/components/WidgetFileUpload.tsx
  kgmt: "KMGT",
  b: "b",
  dragAndDrop: "Drag & Drop Here Or",
  browse: "Browse",
  uploadManifest: "Upload Manifest",
};
